-   id: typescript
    name: typescript
    description: ''
    entry: yarn exec tsc
    language: node
    args: []
    require_serial: false
    additional_dependencies: ["typescript@5.3.3"]
    minimum_pre_commit_version: '0'
