-   id: typescript
    name: typescript
    description: ''
    entry: tsc
    language: node
    'files': \.(ts|tsx)$
    args: []
    require_serial: false
    additional_dependencies: ["typescript@5.3.2"]
    minimum_pre_commit_version: '0'
