-   id: typescript
    name: typescript
    description: ''
    entry: yarn exec tsc
    language: node
    args: []
    require_serial: false
    additional_dependencies: ["typescript@5.6.2"]
    minimum_pre_commit_version: '0'
